### ISSUE TITLE
Not working on iOS Safari 

### ISSUE THREAD

**Issue by pateljoel** [marsidev/react-turnstile#26]
I have tried to use react-turnstile but it doesn't work at all on Safari on mobile devices.

Turnstile tries to verify the action but it just goes black and I don't know what's going on or what happened.

![turnstile-error](https://github.com/marsidev/react-turnstile/assets/64401775/44b3b4f5-36ac-4e62-baab-889aa97c3bf1)

To reproduce:

1. Use any iOS device
2. Go to the demo page: https://react-turnstile.vercel.app/basic
3. Wait for verification and the turnstile captcha is blank.

**Comment by marsidev** [comment]
Hey!

I don't have an iOS device to investigate this issue fully. Can you please:

- check if the issue is still happening (please wait for at least 10 seconds)
- check if the issue does not occur in [this demo](https://demo.turnstile.workers.dev/explicit) (official demo with no libraries)
- provide the iOS version + Safari version that you are using

Also, have you used the library and checked if the issue happens also with your config?

Thanks in advance 🙂

**Comment by marsidev** [comment]
Closed due to inactivity.
