### ISSUE TITLE
onError prop running constantly 

### ISSUE THREAD

**Issue by emmakopf** [marsidev/react-turnstile#79]
Some users on our site are experiencing the onError prop of Turnstile constantly re-running (some claim every 10-15 seconds) even on pages where the turnstile component is not present or being called on
Our implementation: 

```js
<Turnstile
          siteKey={TURNSTILE_CAPTCHA_KEY}
          ref={captchaRef}
          options={{
            size: 'invisible',
          }}
          onError={() => {
            if (captchaRef.current) captchaRef.current.reset()
            setError('Captcha could not be verified; please try again later.')
          }}
          onExpire={() => {
            if (captchaRef.current) captchaRef.current.reset()
          }}
        />
```

Currently on React 16.13.1 and react-turnstile 0.5.1

**Comment by marsidev** [comment]
Hey @emmakopf, sorry to hear that.

When did this start happening? Can you try the latest version (0.7.2)?

**Comment by AsebWebDev** [comment]
@marsidev I can confirm. onError is rerun every 8-10 seconds. We are on version 0.7.2

**Comment by marsidev** [comment]
I see! I noticed this is the expected behavior:

> By default, Turnstile will automatically retry upon encountering a problem. When subsequent failures due to retries are observed, the error callback can be invoked multiple times.

> You can adjust the retry behavior by setting the retry value to never instead of the default auto.

Reference: https://developers.cloudflare.com/turnstile/troubleshooting/client-side-errors/#retry

I created a demo to compare our library with a vanilla widget. In both, the error callback is triggered over and over: https://codesandbox.io/p/devbox/pensive-euclid-kx93vv

As mentioned in the docs, you can set the `retry` property to `"never"` if you prefer no automatic triggers.

```jsx
<Turnstile
  siteKey="2x00000000000000000000AB"
  options={{ retry: "never" }}
/>
```
